# 'Ol Book of Key'
#
BOOK=old-book-of-key
DATA=.
CODE=$(HOME)/Projects/HootingYard/greasepencil
OUTPUT=$(HOME)/Documents/hootingyard-books
WORKSPACE=$(HOME)/hootingyard-workspace
include $(CODE)/Makefile.inc

