# 'Brute Beauty And Valour And Act, Oh, Air, Pride, Plume, Here Buckle!'
#
BOOK=anthology6
DATA=.
CODE=../../../../archive_management/src/hootingyard/greasepencil
OUTPUT=$(HOME)/Documents/hootingyard-books
WORKSPACE=$(HOME)/hootingyard-workspace
include $(CODE)/Makefile.inc

