# 'Funny Mountain'
#
BOOK=funny-mountain
DATA=.
CODE=../../../../archive_management/src/hootingyard/greasepencil
OUTPUT=$(HOME)/Documents/hootingyard-books
WORKSPACE=$(HOME)/hootingyard-workspace
include $(CODE)/Makefile.inc

