# 'Hooting Yard Home Page'
#
BOOK=hooting-yard-home-page
DATA=.
CODE=../../../../greasepencil
OUTPUT=$(HOME)/Documents/hootingyard-books
WORKSPACE=$(HOME)/hootingyard-workspace
include $(CODE)/Makefile.inc

