# 'Obsequies For Lars Talc, Struck By Lightning'
#
BOOK=mr-tritton
DATA=.
CODE=$(abspath ../../code)
OUTPUT=$(abspath ../../bookfiles)
WORKSPACE=$(abspath ../../workspace)
include $(CODE)/Makefile.inc
