# 'Obsequies For Lars Talc, Struck By Lightning'
#
BOOK=lars-talc
DATA=.
CODE=../../../../archive_management/src/hootingyard/greasepencil
OUTPUT=$(HOME)/Documents/hootingyard-books
WORKSPACE=$(HOME)/hootingyard-workspace
include $(CODE)/Makefile.inc

